### ISSUE TITLE
Question about coordinates in voxel map

### ISSUE THREAD

**Issue by ShXiuWei1025** [tsadja/ShaSTA#3]
Hello

Thanks for your wonderful work!

When I study your code. I notice one thing, in det3d/models/second_stage/bird_eye_view.py, 
`def absl_to_relative(self, absolute):
        a1 = (absolute[..., 0] - self.pc_start[0]) / self.voxel_size[0] / self.out_stride 
        a2 = (absolute[..., 1] - self.pc_start[1]) / self.voxel_size[1] / self.out_stride `

`def forward(self, example, batch_centers, num_point):
        batch_size = len(example['bev_feature'])
        ret_maps = [] 

        for batch_idx in range(batch_size):
            xs, ys = self.absl_to_relative(batch_centers[batch_idx])
            feature_map = bilinear_interpolate_torch(example['bev_feature'][batch_idx], xs, ys)`

when you transfer the global coordinates into the relative one, why don't you consider the rotation of vehicle and sensor? Is the voxel map based on the relative coordinates of the lidar sensor?

**Comment by tsadja** [comment]
Hi, sorry for the delayed response. This part of the code comes from CenterPoint. We use the same parameters as CenterPoint for the BEV map formation since we are using CenterPoint detections. Please refer to the CenterPoint [repository](https://github.com/tianweiy/CenterPoint) and [paper](https://arxiv.org/abs/2006.11275) for more information on these design choices.
